# Generated by Django 5.0.4 on 2024-04-28 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2024, 4, 28, 22, 0, 0, 553048, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
