# Generated by Django 5.0.4 on 2024-05-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sujet',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
