# Generated by Django 5.0.4 on 2024-05-22 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_bloodformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresseLab', models.CharField(max_length=255)),
                ('telephoneLab', models.CharField(max_length=15)),
                ('emailLab', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('filePath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('specialtyID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testID', models.AutoField(primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faqID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorie')),
            ],
        ),
    ]
