# Generated by Django 5.0.4 on 2024-05-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_categorie_coordonnees_file_specialite_test_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('prescription', models.ImageField(upload_to='prescriptions/')),
            ],
        ),
    ]
