# Generated by Django 5.0.4 on 2024-05-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rendezvous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'verbose_name_plural': 'RendezVous'},
        ),
    ]
