# Generated by Django 5.0.4 on 2024-05-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_rendezvous_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordonnees',
            new_name='ContactInfo',
        ),
    ]
