# Generated by Django 5.0.4 on 2024-05-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bloodformsubmission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodformsubmission',
            name='user',
        ),
    ]
