# Generated by Django 5.0.4 on 2024-05-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_bloodformsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodformsubmission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
