# Generated by Django 5.0.4 on 2024-05-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_bloodformsubmission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fileID',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='test',
            name='testID',
        ),
        migrations.RemoveField(
            model_name='test',
            name='testName',
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='test_files/ECBU.pdf', upload_to='test_files/'),
        ),
        migrations.AddField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
