# Generated by Django 5.0.4 on 2024-05-28 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_specialty_delete_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodformsubmission',
            name='prescription',
            field=models.FileField(default='default.png', upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='bloodformsubmission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
