# Generated by Django 5.0.4 on 2024-05-29 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_bloodformsubmission_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('test_name', models.CharField(max_length=255)),
                ('apt_notes', models.TextField(blank=True, null=True)),
                ('apt_date', models.DateField()),
                ('apt_time', models.TimeField()),
                ('apt_pres', models.FileField(upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apt_date', 'apt_time'],
            },
        ),
        migrations.DeleteModel(
            name='RendezVous',
        ),
    ]
