# Generated by Django 5.0.4 on 2024-05-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_appointment_delete_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
