# Generated by Django 5.0.4 on 2024-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['apt_date']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='apt_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apt_date',
            field=models.DateTimeField(),
        ),
    ]
