# Generated by Django 5.0.4 on 2024-05-31 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_appointment_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('test_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('result_notes', models.TextField(blank=True, null=True)),
                ('result_date', models.DateTimeField()),
                ('result_file', models.FileField(upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['result_date'],
            },
        ),
    ]
