# Generated by Django 5.0.4 on 2024-05-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_confirmed_resultat_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultat',
            options={},
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='result_date',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='test_name',
        ),
    ]
