# Generated by Django 5.0.4 on 2024-05-31 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_resultat_options_remove_resultat_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
        ),
    ]
