# Generated by Django 5.0.4 on 2024-05-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
